version: '3'
services:
    web:
        image: nginx:${NGINX_VERSION}
        volumes:
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.template
            - .:/var/www/html
        ports:
            - ${NGINX_PORT}:80
        environment:
            - NGINX_PORT
            - NGINX_HOST
        command: /bin/sh -c "envsubst '$$NGINX_PORT $$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        build: ./php
        restart: always
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        environment:
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
        # For Windows fix
        command: ["mysqld", "--innodb-use-native-aio=0"]
        ports:
            - 8989:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
